services:
  back:
    build:
      context: .
      dockerfile: ./dockerfiles/back.Dockerfile
      args:
        - DEV=true
    volumes:
      - ./:/app
    ports:
      - 8004:8004
    env_file:
      - ./env/backend.env
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8004"
    depends_on:
      - db
      - maildev
      - minio
    networks:
      - wp_shared_network
      - internal-net
  
  db:
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    container_name: workpermit-declaration-db
    env_file:
      - ./env/db.env
    ports:
      - '54320:5432'
    volumes: 
      - workpermit_declaration_db:/var/lib/postgresql/data
    networks:
      - internal-net
  
  maildev:
    image: maildev/maildev
    ports:
      - "1081:1080"
      - "1026:1025"
    networks:
      - wp_shared_network

  minio:
    hostname: minio
    image: quay.io/minio/minio
    container_name: minio-workpermit
    command: server /data --console-address :9001
    environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: minio123
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
    volumes:
        - ./storage/data:/data
    ports:
        - "9000:9000"
        - "9001:9001"
    networks:
      - wp_shared_network

volumes:
  workpermit_declaration_db:


networks:
  internal-net:
  wp_shared_network:
    name: wp_shared_network
    driver: bridge      