# Generated by Django 4.0.8 on 2023-01-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_alter_facture_date_alter_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ON', 'Actif'), ('OFF', 'Inactif')], default='ON', max_length=30)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AddField(
            model_name='payer',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paiement.devise')),
            ],
        ),
        migrations.AlterField(
            model_name='payer',
            name='country_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payer_countries', to='paiement.country'),
        ),
        migrations.AlterField(
            model_name='payer',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payer_jobs', to='paiement.job'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_permits_types', to='paiement.permit'),
        ),
    ]
