# Generated by Django 4.0.8 on 2023-01-13 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0003_country_job_remove_facture_date_remove_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ref',
        ),
        migrations.AddField(
            model_name='facture',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
