# Generated by Django 4.0.8 on 2023-01-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_profile_adresse_profile_email'),
        ('paiement', '0004_remove_facture_ref_remove_payment_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.profile'),
            preserve_default=False,
        ),
    ]
