# Generated by Django 4.0.8 on 2023-02-04 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paiement', '0006_jobcategory_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('total_employee', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('first', models.CharField(max_length=100, verbose_name='first name')),
                ('last', models.CharField(max_length=50, verbose_name='last_name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField()),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_declarations', to='paiement.declaration')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_jobs', to='paiement.job')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_job_categories', to='paiement.jobcategory')),
            ],
        ),
    ]
