# Generated by Django 4.0.8 on 2023-03-31 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0007_declaration_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='status',
            field=models.CharField(choices=[('unvalidated', 'Non Validée'), ('validated', 'Validée')], default='unvalidated', max_length=30),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paiement.permit'),
        ),
    ]
