# Generated by Django 4.0.8 on 2023-03-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0008_declaration_status_jobcategory_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='total_employee',
        ),
    ]
