# Generated by Django 4.0.8 on 2023-04-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0009_remove_declaration_total_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='declaration_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='declaration_factures', to='paiement.declaration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='total_agents',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='total_cadres',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='total_ouvriers',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
