# Generated by Django 4.0.8 on 2023-04-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0010_facture_declaration_ref_facture_total_agents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='status',
            field=models.CharField(choices=[('unvalidated', 'Non Validée'), ('validated', 'Validée'), ('billed', 'Facturée')], default='unvalidated', max_length=30),
        ),
    ]
