# Generated by Django 4.0.8 on 2023-05-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0011_alter_declaration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
