# Generated by Django 4.0.8 on 2023-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0012_alter_facture_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('unenrolled', 'Non enrôlé'), ('enrolled', 'Enrôlé')], default='unenrolled', max_length=30),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='status',
            field=models.CharField(choices=[('unsubmitted', 'Non soumise'), ('submitted', 'Soumise'), ('rejected', 'Rejetée'), ('validated', 'Validée'), ('billed', 'Facturée')], default='unvalidated', max_length=30),
        ),
    ]
