# Generated by Django 4.0.8 on 2023-06-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0013_employee_status_alter_declaration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='status',
            field=models.CharField(choices=[('unsubmitted', 'Non soumise'), ('submitted', 'Soumise'), ('rejected', 'Rejetée'), ('validated', 'Validée'), ('billed', 'Facturée')], default='unsubmitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first',
            field=models.CharField(max_length=100, verbose_name='first_name'),
        ),
    ]
