# Generated by Django 4.0.8 on 2023-06-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0014_declaration_reject_reason_alter_declaration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Impayée'), ('paid', 'Payée')], default='unpaid', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
