# Generated by Django 4.0.8 on 2023-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0016_alter_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='permit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
