# Generated by Django 4.2 on 2024-05-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0017_alter_devise_value_alter_permit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarationemployees', related_query_name='declarationemployee', to='paiement.declaration', verbose_name='Déclaration')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarationemployees', related_query_name='declarationemployee', to='paiement.employee', verbose_name='Employé')),
            ],
            options={
                'unique_together': {('declaration', 'employee')},
            },
        ),
    ]
