# Generated by Django 4.2 on 2024-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0018_declarationemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='employees',
            field=models.ManyToManyField(related_name='alldeclarations', related_query_name='alldeclaration', through='paiement.DeclarationEmployee', to='paiement.employee', verbose_name='Employés'),
        ),
    ]
