# Generated by Django 4.2 on 2024-06-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0019_declaration_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
