# Generated by Django 4.2 on 2024-10-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0021_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
