# Generated by Django 4.0.8 on 2022-12-18 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='type name')),
                ('status', models.CharField(choices=[('ON', 'Actif'), ('OFF', 'Inactif')], default='ON', max_length=30)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='profile name')),
                ('status', models.CharField(choices=[('ON', 'Actif'), ('OFF', 'Inactif')], default='ON', max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='staticfiles', verbose_name='profile picture')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profiletype')),
            ],
        ),
    ]
