# Generated by Django 4.0.8 on 2022-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_profile_id_remove_profile_uid_profile_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='poste'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default=622000000, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
