# Generated by Django 4.0.8 on 2022-12-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_agency_region_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code_agence'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code_region'),
        ),
    ]
