# Generated by Django 4.0.8 on 2022-12-27 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_agency_code_alter_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
