# Generated by Django 4.0.8 on 2022-12-27 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_profile_account_alter_profile_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='type name')),
                ('status', models.CharField(choices=[('ON', 'Actif'), ('OFF', 'Inactif')], default='ON', max_length=30)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='uid',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
