# Generated by Django 4.0.8 on 2023-01-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='region_agency', to='authentication.region'),
            preserve_default=False,
        ),
    ]
