# Generated by Django 4.0.8 on 2023-04-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_profile_adresse_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ON', 'Actif'), ('OFF', 'Inactif')], default='ON', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ON', 'Actif'), ('OFF', 'Inactif')], default='ON', max_length=30)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_subs', to='authentication.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ON', 'Actif'), ('OFF', 'Inactif')], default='ON', max_length=30)),
                ('submenu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submenu_actions', to='authentication.submenu')),
            ],
        ),
    ]
