# Generated by Django 4.0.8 on 2023-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_menu_submenu_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='uid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='uid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
