# Generated by Django 4.0.8 on 2023-04-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_action_uid_alter_menu_uid_alter_submenu_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions_list', models.TextField(max_length=255)),
            ],
        ),
    ]
