# Generated by Django 4.0.8 on 2023-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='permissions_code',
            field=models.TextField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
