# Generated by Django 4.0.8 on 2023-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_rename_permissions_code_permission_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codes',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='permission',
            name='list',
            field=models.TextField(max_length=1024),
        ),
    ]
