# Generated by Django 4.0.8 on 2023-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_permission_codes_alter_permission_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codes',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='permission',
            name='list',
            field=models.TextField(max_length=2048),
        ),
    ]
