# Generated by Django 4.0.8 on 2023-06-20 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_remove_profile_account_remove_profile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
