# Generated by Django 4.1.6 on 2023-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_profiletype_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
