# Generated by Django 4.0.10 on 2023-06-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_agency_created_by'),
        ('authentication', '0023_profiletype_comment'),
    ]

    operations = [
    ]
