# Generated by Django 4.2 on 2024-07-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_merge_0022_agency_created_by_0023_profiletype_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='code',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='code',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Code'),
        ),
    ]
