# Generated by Django 5.1.6 on 2025-02-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.TextField(default='Guinea', max_length=100),
        ),
    ]
