name: Build & Deploy
on:
  push:
    branches: [dev]
  # pull_request:
  #   branches:
  #     - release
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy wp declaration
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}} 
          key: ${{secrets.SSH_KEY}} 
          username: ${{ secrets.SSH_USERNAME }} 
     
          script: |
            cd app 
            git pull origin dev
            docker compose -f dc-prod.yml down
            docker builder purne -f -a
            docker compose -f dc-prod.yml up --build -d 
